### ISSUE TITLE
Treball En Equip - "La Liga de los Cohetes"

### ISSUE THREAD

**Issue by u1980756** [TreballEquip/Treball#1]
**Part artística**
- [x] Logo en SVG
- [x] Animació al Logo
- [x] Utilitzar el logo al menú del joc i activar l’animació al passar per sobre

**Part programació**
- [x] Fer un menú principal en VUE.js 1p (Ha de tenir un estil coherent amb el joc)
- [x] Implementar el joc en Phaser.io 
- [x] Implementar un menú de pausa dins del joc (Pot estar fet en VUE.js o en Phaser.io)

**Altres**
- [x] Realitzar Wiki

**Comment by ghost** [comment]
No hem fet el menú en VUE perquè no era necessari amb la funcionalitat que volíem que tingués
